### PR TITLE
Update setup.py

### LINKED ISSUE #2: Ask the user the name of the cpp file which will be created as command line argument
CURRENT SCENARIO :- 
The script makes a file named `test.cpp` in a separate folder named `cp` just a directory outside the repo.
in short it makes file `../cp/test.cpp`

EXPECTED SCENARIO :- 
The user sent the name of the file via the command line arguments and the file should be created with that name
- if the file name already exist then create a file with a number proceeding it `<file_name>_1.cpp` or `<file_name>_2.cpp` or `<file_name>_3.cpp` and so on

### PR DESCRIPTION
**Pull request by OrangoMango**

### CODE REVIEW

**Comment by OrangoMango** [comment]
You need only to insert the file name without extension

**Comment by OrangoMango** [comment]
But if you merge this pull request, my forked repository automatically created, will be deleted?
And if I delete this forked repository, are you able to merge this pull request?

**Review by Arsenic-ATG — APPROVED** [review]

**Comment by Arsenic-ATG** [comment]
Thanks @OrangoMango for the contribution 🏅

**Comment by Arsenic-ATG** [comment]
> But if you merge this pull request, my forked repository automatically created, will be deleted?
> And if I delete this forked repository, are you able to merge this pull request?

Ans1 . No, after merging, it is totally up to you if you want to delete your fork or not.

Ans2. YES, once you have created a PR then even if you delete the fork then it will not affect your contribution to the upstream repo ( but you would be no longer be able to make further changes to the repo and have to re fork it order to do so )

**Comment by OrangoMango** [comment]
> > But if you merge this pull request, my forked repository automatically created, will be deleted?
> > And if I delete this forked repository, are you able to merge this pull request?
> 
> Ans1 . No, after merging, it is totally up to you if you want to delete your fork or not.
> 
> Ans2. YES, once you have created a PR then even if you delete the fork then it will not affect your contribution to the upstream repo ( but you would be no longer be able to make further changes to the repo and have to re fork it order to do so )

Thank you very much I don't contribute very much on github so I'm new. I only do repositories on GitHub

**Pull request merged**
